#!/usr/bin/env bash
# -*- coding: utf-8 -*-

PROJECT_NAME=koica

# Vars Dir
ROOT_DIR="`pwd`"
RESOURCES_DIR="$ROOT_DIR/resources"
RESOURCES_DB_DIR="$RESOURCES_DIR/db"
PROVISION_DIR="$ROOT_DIR/provision/ansible"
SOURCE_DIR="$ROOT_DIR/src"
STATIC_DIR="$SOURCE_DIR/staticfiles/"

PYTHON_VERSION=2.7.9
PYENV_NAME="${PROJECT_NAME}"

GVM_NAME="${PROJECT_NAME}"
GVM_PATHS_NAME="{src, pkg, bin}"

KEYS_DIR="$HOME/.ssh"
KEY_FILE="$KEYS_DIR/$PROJECT_NAME.pem"
DEPLOY_SOURCE_DIR=$STATIC_DIR
DEPLOY_DEST_DIR=/home/ubuntu/$PROJECT_NAME/src/staticfiles/
# DEPLOY_SERVER=52.39.180.62

DEPLOY_ACCOUNT=ubuntu

DJANGO_IP=0.0.0.0
DJANGO_PORT=8080
DJANGO_SETTINGS_DEFAULT=$PROJECT_NAME.settings
DJANGO_SETTINGS_DEV=$PROJECT_NAME.settings_dev
DJANGO_SETTINGS_TEST=$PROJECT_NAME.settings_test

NAME_DATABASE=$PROJECT_NAME.sqlite3
NAME_DATABASE_DEV=$PROJECT_NAME-dev.sqlite3
NAME_DATABASE_TEST=$PROJECT_NAME-test.sqlite3

PATH_INVENTORY="$PROVISION_DIR/inventories/aws/production"
USER=$DEPLOY_ACCOUNT
PRIVATE_KEY="$KEY_FILE"
EXTRA_VARS="user=ubuntu"

VIRTUALENV=$PROJECT_NAME
VIRTUALENVS_PATH="$HOME_DIR/.virtualenvs"
VIRTUALENV_PATH="$VIRTUALENVS_PATH/$VIRTUALENV"
VIRTUALENV_FILE_ACTIVATE="$VIRTUALENV_PATH/bin/activate"
VIRTUALENV_FILE_POSTACTIVATE="$VIRTUALENV_PATH/bin/postactivate"
